### ISSUE TITLE
Docker-Obs-Streaming 

### ISSUE THREAD

**Issue by jammsen** [R0GGER/docker#1]
Hey,
while im trying to get the OBS-Streaming Dockercontainer to build i get the error:
Step 13/22 : RUN apt-get update
 ---> Running in be0380b5ccbf
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Ign:2 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial InRelease
Ign:3 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial Release
Ign:4 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 Packages
Ign:5 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all Packages
Hit:6 http://archive.ubuntu.com/ubuntu xenial InRelease
Ign:4 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 Packages
Ign:5 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all Packages
Hit:7 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Ign:4 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 Packages
Ign:5 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all Packages
Ign:4 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 Packages
Hit:8 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Ign:5 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all Packages
Ign:4 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 Packages
Ign:5 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all Packages
Err:4 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:5 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all Packages
Reading package lists...
W: The repository 'http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/mc3man/trusty-media/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100

Could you look at that?

By my estimation you should either setup the ubuntuversion to a certain value or insert this:
sudo add-apt-repository ppa:mc3man/xerus-media
instead of 
sudo add-apt-repository ppa:mc3man/trusty-media

**Comment by R0GGER** [comment]
Please try this one: https://github.com/R0GGER/mistserver
